version: "3"

services:
  collector:
    image: florentio/aiven_hw:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./certs:/usr/src/app/certs
    entrypoint: python3 -u main.py --collector

  persistor:
    image: florentio/aiven_hw:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./certs:/usr/src/app/certs
    entrypoint: python3 -u main.py --persistor




